#!/bin/sh
# chkconfig: 235 97 20
# description: Oracle auto start-stop scripts.
#
# Set ORA_HOME to be equivalent to the $ORACLE_HOME from which 
# you wish to execute dbstart and dbshut.
#
# Set ORA_OWNER to the user id of the owner of the Oracle database
# in ORA_HOME
ORA_HOME=/u01/app/oracle/product/12.1.0/dbhome_1
ORA_OWNER=oracle

if [ ! -f $ORA_HOME/bin/dbstart ]
then
	echo"Oracle startup: cannot start"
	exit
fi

case "$1" in
	'start')
		# Start the Oracle databases:
		# The fillowing command assumes that oracle login
		# will not prompt the user for any values
		# Add "&" if you want startup run as a background process.
		su $ORA_OWNER -c "$ORA_HOME/bin/dbstart $ORA_HOME"
		touch /var/lock/subsys/dbora
		;;
	'stop')
		# Stop the Oracle databases:
                # The fillowing command assumes that oracle login
                # will not prompt the user for any values
                # Add "&" if you want startup run as a background process.
                su $ORA_OWNER -c "$ORA_HOME/bin/dbshut $ORA_HOME"
                rm -f /var/lock/subsys/dbora
                ;;

esac
